Change to domain name mapping
opencybersecurityalliance/stix-shifter pull request #1342
Opened 2023-02-23 16:57 UTC by KaneBrennan132

Changed the domain-name mapping as DOMAINNAME(domainid) is for the Qradar tenancy domains.

User documentation changes are planned.

2023-02-23 16:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opencybersecurityalliance/stix-shifter?pullRequest=1342) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opencybersecurityalliance/stix-shifter?pullRequest=1342) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opencybersecurityalliance/stix-shifter?pullRequest=1342) it.</sub>

2023-02-24 12:42 UTC, delliott90 commented on stix_shifter_modules/qradar/stix_translation/json/stix_2_1/to_stix_map.json
> +  "qradardomain": [
You should remove the entry that's currently under `dnsdomainname` a few lines down. We don't want to write duplicated data in multiple properties. In fact, if dnsdomainname is truly a domain, it shouldn't be writing the value to the url object.

2023-02-24 12:43 UTC, delliott90 requested changes
Any changes to the `to-stix` mapping files should be reflected in the `from-stix` files as well.

2023-03-30 13:47 UTC, KaneBrennan132 commented
Changed dnsdomainname entry to only write to domain-name
Changed alias used by DNS request domain in event search to use the alias dnsdomainname, removed domainname entry as it is no longer required. 
Updated Unit Tests to reflect changes
Updated Docs to reflect changes

2023-03-31 12:14 UTC, delliott90 approved these changes

2023-03-31 12:15 UTC, merged