Validator review code change
opencybersecurityalliance/stix-shifter pull request #739
Opened 2021-11-19 03:49 UTC by JyotiWhcl

Code change on validator review comments

2021-11-19 13:34 UTC, mdazam1942 requested changes
It looks like all the file has changed somehow! not sure what's the update. you should create a new branch and submit your pr with the specific change that you made.

2021-11-26 11:39 UTC, JyotiWhcl commented
@mdazam1942 , @delliott90 
Updated PR with changes in file 'results_connector.py'.
Requesting review again.

2021-11-29 14:59 UTC, mdazam1942 requested changes

2021-11-30 12:13 UTC, JyotiWhcl commented
@mdazam1942 , @delliott90 
Updated PR for, Reverted changes in gitignore file.
Requesting review again.

2021-11-30 13:47 UTC, mdazam1942 approved these changes

2021-11-30 13:48 UTC, merged